const boot=document.getElementById('boot');const enter=document.getElementById('enter');const voiceIntro=document.getElementById('voiceIntro');const voiceToggle=document.getElementById('voiceToggle');const chatVoice=document.getElementById('chatVoice');const status=document.getElementById('agentStatus');
let voiceEnabled=false;let introDone=false;
const speak=(text)=>{if(!voiceEnabled||!('speechSynthesis'in window))return;window.speechSynthesis.cancel();const u=new SpeechSynthesisUtterance(text);u.rate=.95;u.pitch=1.02;u.volume=.9;window.speechSynthesis.speak(u)};
const launch=()=>{if(introDone)return;introDone=true;boot.classList.add('exit');document.body.classList.remove('lock');status.textContent='Welcome — explore Awais\'s work';if(voiceEnabled)speak('Welcome to Awais Irshad portfolio. I am Awais AI Agent. Explore his projects, skills and work.');setTimeout(()=>boot.remove(),950)};
enter?.addEventListener('click',launch);
voiceIntro?.addEventListener('click',()=>{voiceEnabled=true;voiceIntro.textContent='✓ Voice introduction enabled';voiceIntro.style.color='#c8ff3d';speak('Hi, welcome to Awais Irshad portfolio. I am Awais AI Agent, your portfolio guide.');});
voiceToggle?.addEventListener('click',()=>{voiceEnabled=!voiceEnabled;voiceToggle.textContent=voiceEnabled?'◉ VOICE ON':'◉ VOICE';voiceToggle.style.color=voiceEnabled?'#c8ff3d':'';if(!voiceEnabled)window.speechSynthesis?.cancel();else speak('Voice assistant is now on.');});
setTimeout(launch,6500);
const menu=document.getElementById('menu'),nav=document.querySelector('nav');menu?.addEventListener('click',()=>{const open=nav.dataset.open==='1';nav.dataset.open=open?'0':'1';nav.style.display=open?'':'flex';if(!open)Object.assign(nav.style,{position:'absolute',top:'64px',left:'0',right:'0',padding:'20px',background:'#050705',flexDirection:'column',borderBottom:'1px solid #252b22'});});
document.querySelectorAll('nav a').forEach(a=>a.addEventListener('click',()=>{if(innerWidth<=850){nav.style.display='';nav.dataset.open='0'}}));
const responses={
 about:'Awais Irshad is an AI/ML Engineer focused on Python, machine learning, generative AI, backend development and automation. He enjoys turning real problems into useful software.',
 projects:'Awais has built projects including LedgerIQ AI, a financial intelligence application, Todo App, and Sky Briefing. You can explore the repositories in the Selected Work section.',
 tech:'His portfolio highlights Python, NumPy, Pandas, Scikit-learn, LLM applications, RAG, prompt engineering, Django, APIs, SQLite, n8n, Docker, Streamlit and GitHub.',
 contact:'You can contact Awais through WhatsApp, email or LinkedIn. WhatsApp: +92 341 2850260. Email: awaisirshad336012@gmail.com.'
};
function answer(q){const s=q.toLowerCase();if(s.includes('contact')||s.includes('whatsapp')||s.includes('email')||s.includes('linkedin'))return responses.contact;if(s.includes('project')||s.includes('build')||s.includes('work'))return responses.projects;if(s.includes('tech')||s.includes('skill')||s.includes('stack')||s.includes('use'))return responses.tech;if(s.includes('who')||s.includes('about')||s.includes('awais'))return responses.about;return 'I can tell you about Awais, his projects, technologies, or contact details. Try asking about his projects or tech stack.';}
const log=document.getElementById('chatLog'),form=document.getElementById('chatForm'),input=document.getElementById('chatInput');
function sendQuestion(q){if(!q)return;const u=document.createElement('div');u.className='msg user-msg';u.textContent=q;log.appendChild(u);const a=document.createElement('div');a.className='msg agent-msg';const text=answer(q);a.textContent=text;log.appendChild(a);log.scrollTop=log.scrollHeight;speak(text);}
form?.addEventListener('submit',e=>{e.preventDefault();const q=input.value.trim();input.value='';sendQuestion(q)});
document.querySelectorAll('.quick-questions button').forEach(b=>b.addEventListener('click',()=>sendQuestion(b.dataset.question)));
chatVoice?.addEventListener('click',()=>{voiceEnabled=!voiceEnabled;chatVoice.textContent=voiceEnabled?'VOICE ON':'VOICE OFF';chatVoice.classList.toggle('off',!voiceEnabled);if(voiceEnabled)speak('Voice mode is on. Ask me anything about Awais.');else window.speechSynthesis?.cancel();});
// Optional browser speech recognition: visitors can speak directly to the agent when supported.
const SpeechRecognition=window.SpeechRecognition||window.webkitSpeechRecognition;if(SpeechRecognition&&input){const mic=document.createElement('button');mic.type='button';mic.textContent='🎙';mic.title='Speak to Awais AI';mic.style.cssText='width:42px;background:#10140e;color:#c8ff3d;border:0;border-left:1px solid #242a21;cursor:pointer';form.insertBefore(mic,form.lastElementChild);const rec=new SpeechRecognition();rec.lang='en-US';rec.interimResults=false;mic.addEventListener('click',()=>{rec.start();mic.textContent='…'});rec.onresult=e=>{input.value=e.results[0][0].transcript;mic.textContent='🎙';form.requestSubmit()};rec.onerror=()=>mic.textContent='🎙';rec.onend=()=>mic.textContent='🎙'}